#!/usr/bin/env php
<?php

use CodeIgniter\Boot;
use Config\Paths;

define('FCPATH', __DIR__ . DIRECTORY_SEPARATOR);
define('COMPOSER_PATH', __DIR__ . '/vendor/autoload.php');

require FCPATH . 'app/Config/Paths.php';

$paths = new Paths();

require $paths->systemDirectory . '/Boot.php';

Boot::bootSpark($paths);
