<?php

namespace Config;

use CodeIgniter\Config\BaseConfig;

/**
 * Content-Security-Policy runtime values (per request).
 *
 * The nonce is generated by ContentSecurityPolicyFilter::before and used in
 * the CSP header and (when enabled) injected into inline script/style tags.
 */
class Csp extends BaseConfig
{
    /**
     * Per-request nonce (base64). Set by ContentSecurityPolicyFilter only.
     */
    public string $nonce = '';

    /**
     * When true, HTML responses are post-processed to add nonce="..." to
     * inline &lt;script&gt; and &lt;style&gt; tags that lack src and nonce.
     */
    public bool $injectNonceIntoHtml = true;

    /**
     * Allow eval() / new Function() (maps to script-src 'unsafe-eval').
     * Keep false unless a library breaks after CSP tightening; then prefer
     * replacing that library or loading it differently.
     */
    public bool $allowUnsafeEval = false;
}
