<!-- Hidden input to store the selected value -->
<input type="hidden" id="countrySelect" value="+212">

<!-- Custom Dropdown Trigger -->
<div class="custom-select-trigger" id="countryTrigger" tabindex="0">
    <span class="flag-icon flag-icon-ma" id="selectedFlag"></span>
    <i class="fa-solid fa-chevron-down ms-2" style="font-size: 0.7rem; color: #666;"></i>
</div>

<!-- Custom Dropdown Options -->
<div class="custom-options" id="countryOptions">
    <!-- Common -->
    <div class="custom-option selected" data-value="+212" data-flag="ma"><span class="flag-icon flag-icon-ma"></span></div>
    <div class="custom-option" data-value="+971" data-flag="ae"><span class="flag-icon flag-icon-ae"></span></div>
    <div class="custom-option" data-value="+966" data-flag="sa"><span class="flag-icon flag-icon-sa"></span></div>
    <div class="custom-option" data-value="+974" data-flag="qa"><span class="flag-icon flag-icon-qa"></span></div>
    <div class="custom-option" data-value="+33" data-flag="fr"><span class="flag-icon flag-icon-fr"></span></div>
    <div class="custom-option" data-value="+44" data-flag="gb"><span class="flag-icon flag-icon-gb"></span></div>
    <div class="custom-option" data-value="+1" data-flag="us"><span class="flag-icon flag-icon-us"></span></div>

    <!-- All Countries -->
    <div class="custom-option" data-value="+93" data-flag="af"><span class="flag-icon flag-icon-af"></span></div>
    <div class="custom-option" data-value="+355" data-flag="al"><span class="flag-icon flag-icon-al"></span></div>
    <div class="custom-option" data-value="+213" data-flag="dz"><span class="flag-icon flag-icon-dz"></span></div>
    <div class="custom-option" data-value="+376" data-flag="ad"><span class="flag-icon flag-icon-ad"></span></div>
    <div class="custom-option" data-value="+244" data-flag="ao"><span class="flag-icon flag-icon-ao"></span></div>
    <div class="custom-option" data-value="+54" data-flag="ar"><span class="flag-icon flag-icon-ar"></span></div>
    <div class="custom-option" data-value="+374" data-flag="am"><span class="flag-icon flag-icon-am"></span></div>
    <div class="custom-option" data-value="+61" data-flag="au"><span class="flag-icon flag-icon-au"></span></div>
    <div class="custom-option" data-value="+43" data-flag="at"><span class="flag-icon flag-icon-at"></span></div>
    <div class="custom-option" data-value="+994" data-flag="az"><span class="flag-icon flag-icon-az"></span></div>
    <div class="custom-option" data-value="+973" data-flag="bh"><span class="flag-icon flag-icon-bh"></span></div>
    <div class="custom-option" data-value="+880" data-flag="bd"><span class="flag-icon flag-icon-bd"></span></div>
    <div class="custom-option" data-value="+375" data-flag="by"><span class="flag-icon flag-icon-by"></span></div>
    <div class="custom-option" data-value="+32" data-flag="be"><span class="flag-icon flag-icon-be"></span></div>
    <div class="custom-option" data-value="+501" data-flag="bz"><span class="flag-icon flag-icon-bz"></span></div>
    <div class="custom-option" data-value="+229" data-flag="bj"><span class="flag-icon flag-icon-bj"></span></div>
    <div class="custom-option" data-value="+975" data-flag="bt"><span class="flag-icon flag-icon-bt"></span></div>
    <div class="custom-option" data-value="+591" data-flag="bo"><span class="flag-icon flag-icon-bo"></span></div>
    <div class="custom-option" data-value="+387" data-flag="ba"><span class="flag-icon flag-icon-ba"></span></div>
    <div class="custom-option" data-value="+267" data-flag="bw"><span class="flag-icon flag-icon-bw"></span></div>
    <div class="custom-option" data-value="+55" data-flag="br"><span class="flag-icon flag-icon-br"></span></div>
    <div class="custom-option" data-value="+673" data-flag="bn"><span class="flag-icon flag-icon-bn"></span></div>
    <div class="custom-option" data-value="+359" data-flag="bg"><span class="flag-icon flag-icon-bg"></span></div>
    <div class="custom-option" data-value="+226" data-flag="bf"><span class="flag-icon flag-icon-bf"></span></div>
    <div class="custom-option" data-value="+257" data-flag="bi"><span class="flag-icon flag-icon-bi"></span></div>
    <div class="custom-option" data-value="+855" data-flag="kh"><span class="flag-icon flag-icon-kh"></span></div>
    <div class="custom-option" data-value="+237" data-flag="cm"><span class="flag-icon flag-icon-cm"></span></div>
    <div class="custom-option" data-value="+1" data-flag="ca"><span class="flag-icon flag-icon-ca"></span></div>
    <div class="custom-option" data-value="+238" data-flag="cv"><span class="flag-icon flag-icon-cv"></span></div>
    <div class="custom-option" data-value="+236" data-flag="cf"><span class="flag-icon flag-icon-cf"></span></div>
    <div class="custom-option" data-value="+235" data-flag="td"><span class="flag-icon flag-icon-td"></span></div>
    <div class="custom-option" data-value="+56" data-flag="cl"><span class="flag-icon flag-icon-cl"></span></div>
    <div class="custom-option" data-value="+86" data-flag="cn"><span class="flag-icon flag-icon-cn"></span></div>
    <div class="custom-option" data-value="+57" data-flag="co"><span class="flag-icon flag-icon-co"></span></div>
    <div class="custom-option" data-value="+269" data-flag="km"><span class="flag-icon flag-icon-km"></span></div>
    <div class="custom-option" data-value="+243" data-flag="cd"><span class="flag-icon flag-icon-cd"></span></div>
    <div class="custom-option" data-value="+506" data-flag="cr"><span class="flag-icon flag-icon-cr"></span></div>
    <div class="custom-option" data-value="+385" data-flag="hr"><span class="flag-icon flag-icon-hr"></span></div>
    <div class="custom-option" data-value="+53" data-flag="cu"><span class="flag-icon flag-icon-cu"></span></div>
    <div class="custom-option" data-value="+357" data-flag="cy"><span class="flag-icon flag-icon-cy"></span></div>
    <div class="custom-option" data-value="+420" data-flag="cz"><span class="flag-icon flag-icon-cz"></span></div>
    <div class="custom-option" data-value="+45" data-flag="dk"><span class="flag-icon flag-icon-dk"></span></div>
    <div class="custom-option" data-value="+253" data-flag="dj"><span class="flag-icon flag-icon-dj"></span></div>
    <div class="custom-option" data-value="+1767" data-flag="dm"><span class="flag-icon flag-icon-dm"></span></div>
    <div class="custom-option" data-value="+1809" data-flag="do"><span class="flag-icon flag-icon-do"></span></div>
    <div class="custom-option" data-value="+593" data-flag="ec"><span class="flag-icon flag-icon-ec"></span></div>
    <div class="custom-option" data-value="+20" data-flag="eg"><span class="flag-icon flag-icon-eg"></span></div>
    <div class="custom-option" data-value="+503" data-flag="sv"><span class="flag-icon flag-icon-sv"></span></div>
    <div class="custom-option" data-value="+240" data-flag="gq"><span class="flag-icon flag-icon-gq"></span></div>
    <div class="custom-option" data-value="+291" data-flag="er"><span class="flag-icon flag-icon-er"></span></div>
    <div class="custom-option" data-value="+372" data-flag="ee"><span class="flag-icon flag-icon-ee"></span></div>
    <div class="custom-option" data-value="+251" data-flag="et"><span class="flag-icon flag-icon-et"></span></div>
    <div class="custom-option" data-value="+679" data-flag="fj"><span class="flag-icon flag-icon-fj"></span></div>
    <div class="custom-option" data-value="+358" data-flag="fi"><span class="flag-icon flag-icon-fi"></span></div>
    <div class="custom-option" data-value="+241" data-flag="ga"><span class="flag-icon flag-icon-ga"></span></div>
    <div class="custom-option" data-value="+220" data-flag="gm"><span class="flag-icon flag-icon-gm"></span></div>
    <div class="custom-option" data-value="+995" data-flag="ge"><span class="flag-icon flag-icon-ge"></span></div>
    <div class="custom-option" data-value="+49" data-flag="de"><span class="flag-icon flag-icon-de"></span></div>
    <div class="custom-option" data-value="+233" data-flag="gh"><span class="flag-icon flag-icon-gh"></span></div>
    <div class="custom-option" data-value="+30" data-flag="gr"><span class="flag-icon flag-icon-gr"></span></div>
    <div class="custom-option" data-value="+502" data-flag="gt"><span class="flag-icon flag-icon-gt"></span></div>
    <div class="custom-option" data-value="+224" data-flag="gn"><span class="flag-icon flag-icon-gn"></span></div>
    <div class="custom-option" data-value="+245" data-flag="gw"><span class="flag-icon flag-icon-gw"></span></div>
    <div class="custom-option" data-value="+592" data-flag="gy"><span class="flag-icon flag-icon-gy"></span></div>
    <div class="custom-option" data-value="+509" data-flag="ht"><span class="flag-icon flag-icon-ht"></span></div>
    <div class="custom-option" data-value="+504" data-flag="hn"><span class="flag-icon flag-icon-hn"></span></div>
    <div class="custom-option" data-value="+852" data-flag="hk"><span class="flag-icon flag-icon-hk"></span></div>
    <div class="custom-option" data-value="+36" data-flag="hu"><span class="flag-icon flag-icon-hu"></span></div>
    <div class="custom-option" data-value="+354" data-flag="is"><span class="flag-icon flag-icon-is"></span></div>
    <div class="custom-option" data-value="+91" data-flag="in"><span class="flag-icon flag-icon-in"></span></div>
    <div class="custom-option" data-value="+62" data-flag="id"><span class="flag-icon flag-icon-id"></span></div>
    <div class="custom-option" data-value="+98" data-flag="ir"><span class="flag-icon flag-icon-ir"></span></div>
    <div class="custom-option" data-value="+964" data-flag="iq"><span class="flag-icon flag-icon-iq"></span></div>
    <div class="custom-option" data-value="+353" data-flag="ie"><span class="flag-icon flag-icon-ie"></span></div>
    <div class="custom-option" data-value="+972" data-flag="il"><span class="flag-icon flag-icon-il"></span></div>
    <div class="custom-option" data-value="+39" data-flag="it"><span class="flag-icon flag-icon-it"></span></div>
    <div class="custom-option" data-value="+225" data-flag="ci"><span class="flag-icon flag-icon-ci"></span></div>
    <div class="custom-option" data-value="+1876" data-flag="jm"><span class="flag-icon flag-icon-jm"></span></div>
    <div class="custom-option" data-value="+81" data-flag="jp"><span class="flag-icon flag-icon-jp"></span></div>
    <div class="custom-option" data-value="+962" data-flag="jo"><span class="flag-icon flag-icon-jo"></span></div>
    <div class="custom-option" data-value="+7" data-flag="kz"><span class="flag-icon flag-icon-kz"></span></div>
    <div class="custom-option" data-value="+254" data-flag="ke"><span class="flag-icon flag-icon-ke"></span></div>
    <div class="custom-option" data-value="+383" data-flag="xk"><span class="flag-icon flag-icon-xk"></span></div>
    <div class="custom-option" data-value="+965" data-flag="kw"><span class="flag-icon flag-icon-kw"></span></div>
    <div class="custom-option" data-value="+996" data-flag="kg"><span class="flag-icon flag-icon-kg"></span></div>
    <div class="custom-option" data-value="+856" data-flag="la"><span class="flag-icon flag-icon-la"></span></div>
    <div class="custom-option" data-value="+371" data-flag="lv"><span class="flag-icon flag-icon-lv"></span></div>
    <div class="custom-option" data-value="+961" data-flag="lb"><span class="flag-icon flag-icon-lb"></span></div>
    <div class="custom-option" data-value="+266" data-flag="ls"><span class="flag-icon flag-icon-ls"></span></div>
    <div class="custom-option" data-value="+231" data-flag="lr"><span class="flag-icon flag-icon-lr"></span></div>
    <div class="custom-option" data-value="+218" data-flag="ly"><span class="flag-icon flag-icon-ly"></span></div>
    <div class="custom-option" data-value="+423" data-flag="li"><span class="flag-icon flag-icon-li"></span></div>
    <div class="custom-option" data-value="+370" data-flag="lt"><span class="flag-icon flag-icon-lt"></span></div>
    <div class="custom-option" data-value="+352" data-flag="lu"><span class="flag-icon flag-icon-lu"></span></div>
    <div class="custom-option" data-value="+389" data-flag="mk"><span class="flag-icon flag-icon-mk"></span></div>
    <div class="custom-option" data-value="+261" data-flag="mg"><span class="flag-icon flag-icon-mg"></span></div>
    <div class="custom-option" data-value="+265" data-flag="mw"><span class="flag-icon flag-icon-mw"></span></div>
    <div class="custom-option" data-value="+60" data-flag="my"><span class="flag-icon flag-icon-my"></span></div>
    <div class="custom-option" data-value="+223" data-flag="ml"><span class="flag-icon flag-icon-ml"></span></div>
    <div class="custom-option" data-value="+356" data-flag="mt"><span class="flag-icon flag-icon-mt"></span></div>
    <div class="custom-option" data-value="+222" data-flag="mr"><span class="flag-icon flag-icon-mr"></span></div>
    <div class="custom-option" data-value="+230" data-flag="mu"><span class="flag-icon flag-icon-mu"></span></div>
    <div class="custom-option" data-value="+52" data-flag="mx"><span class="flag-icon flag-icon-mx"></span></div>
    <div class="custom-option" data-value="+373" data-flag="md"><span class="flag-icon flag-icon-md"></span></div>
    <div class="custom-option" data-value="+377" data-flag="mc"><span class="flag-icon flag-icon-mc"></span></div>
    <div class="custom-option" data-value="+976" data-flag="mn"><span class="flag-icon flag-icon-mn"></span></div>
    <div class="custom-option" data-value="+382" data-flag="me"><span class="flag-icon flag-icon-me"></span></div>
    <div class="custom-option" data-value="+258" data-flag="mz"><span class="flag-icon flag-icon-mz"></span></div>
    <div class="custom-option" data-value="+95" data-flag="mm"><span class="flag-icon flag-icon-mm"></span></div>
    <div class="custom-option" data-value="+264" data-flag="na"><span class="flag-icon flag-icon-na"></span></div>
    <div class="custom-option" data-value="+977" data-flag="np"><span class="flag-icon flag-icon-np"></span></div>
    <div class="custom-option" data-value="+31" data-flag="nl"><span class="flag-icon flag-icon-nl"></span></div>
    <div class="custom-option" data-value="+64" data-flag="nz"><span class="flag-icon flag-icon-nz"></span></div>
    <div class="custom-option" data-value="+505" data-flag="ni"><span class="flag-icon flag-icon-ni"></span></div>
    <div class="custom-option" data-value="+227" data-flag="ne"><span class="flag-icon flag-icon-ne"></span></div>
    <div class="custom-option" data-value="+234" data-flag="ng"><span class="flag-icon flag-icon-ng"></span></div>
    <div class="custom-option" data-value="+47" data-flag="no"><span class="flag-icon flag-icon-no"></span></div>
    <div class="custom-option" data-value="+968" data-flag="om"><span class="flag-icon flag-icon-om"></span></div>
    <div class="custom-option" data-value="+92" data-flag="pk"><span class="flag-icon flag-icon-pk"></span></div>
    <div class="custom-option" data-value="+970" data-flag="ps"><span class="flag-icon flag-icon-ps"></span></div>
    <div class="custom-option" data-value="+507" data-flag="pa"><span class="flag-icon flag-icon-pa"></span></div>
    <div class="custom-option" data-value="+675" data-flag="pg"><span class="flag-icon flag-icon-pg"></span></div>
    <div class="custom-option" data-value="+595" data-flag="py"><span class="flag-icon flag-icon-py"></span></div>
    <div class="custom-option" data-value="+51" data-flag="pe"><span class="flag-icon flag-icon-pe"></span></div>
    <div class="custom-option" data-value="+63" data-flag="ph"><span class="flag-icon flag-icon-ph"></span></div>
    <div class="custom-option" data-value="+48" data-flag="pl"><span class="flag-icon flag-icon-pl"></span></div>
    <div class="custom-option" data-value="+351" data-flag="pt"><span class="flag-icon flag-icon-pt"></span></div>
    <div class="custom-option" data-value="+40" data-flag="ro"><span class="flag-icon flag-icon-ro"></span></div>
    <div class="custom-option" data-value="+7" data-flag="ru"><span class="flag-icon flag-icon-ru"></span></div>
    <div class="custom-option" data-value="+250" data-flag="rw"><span class="flag-icon flag-icon-rw"></span></div>
    <div class="custom-option" data-value="+239" data-flag="st"><span class="flag-icon flag-icon-st"></span></div>
    <div class="custom-option" data-value="+221" data-flag="sn"><span class="flag-icon flag-icon-sn"></span></div>
    <div class="custom-option" data-value="+381" data-flag="rs"><span class="flag-icon flag-icon-rs"></span></div>
    <div class="custom-option" data-value="+248" data-flag="sc"><span class="flag-icon flag-icon-sc"></span></div>
    <div class="custom-option" data-value="+232" data-flag="sl"><span class="flag-icon flag-icon-sl"></span></div>
    <div class="custom-option" data-value="+65" data-flag="sg"><span class="flag-icon flag-icon-sg"></span></div>
    <div class="custom-option" data-value="+421" data-flag="sk"><span class="flag-icon flag-icon-sk"></span></div>
    <div class="custom-option" data-value="+386" data-flag="si"><span class="flag-icon flag-icon-si"></span></div>
    <div class="custom-option" data-value="+252" data-flag="so"><span class="flag-icon flag-icon-so"></span></div>
    <div class="custom-option" data-value="+27" data-flag="za"><span class="flag-icon flag-icon-za"></span></div>
    <div class="custom-option" data-value="+82" data-flag="kr"><span class="flag-icon flag-icon-kr"></span></div>
    <div class="custom-option" data-value="+211" data-flag="ss"><span class="flag-icon flag-icon-ss"></span></div>
    <div class="custom-option" data-value="+34" data-flag="es"><span class="flag-icon flag-icon-es"></span></div>
    <div class="custom-option" data-value="+94" data-flag="lk"><span class="flag-icon flag-icon-lk"></span></div>
    <div class="custom-option" data-value="+249" data-flag="sd"><span class="flag-icon flag-icon-sd"></span></div>
    <div class="custom-option" data-value="+597" data-flag="sr"><span class="flag-icon flag-icon-sr"></span></div>
    <div class="custom-option" data-value="+268" data-flag="sz"><span class="flag-icon flag-icon-sz"></span></div>
    <div class="custom-option" data-value="+46" data-flag="se"><span class="flag-icon flag-icon-se"></span></div>
    <div class="custom-option" data-value="+41" data-flag="ch"><span class="flag-icon flag-icon-ch"></span></div>
    <div class="custom-option" data-value="+963" data-flag="sy"><span class="flag-icon flag-icon-sy"></span></div>
    <div class="custom-option" data-value="+886" data-flag="tw"><span class="flag-icon flag-icon-tw"></span></div>
    <div class="custom-option" data-value="+992" data-flag="tj"><span class="flag-icon flag-icon-tj"></span></div>
    <div class="custom-option" data-value="+255" data-flag="tz"><span class="flag-icon flag-icon-tz"></span></div>
    <div class="custom-option" data-value="+66" data-flag="th"><span class="flag-icon flag-icon-th"></span></div>
    <div class="custom-option" data-value="+670" data-flag="tl"><span class="flag-icon flag-icon-tl"></span></div>
    <div class="custom-option" data-value="+228" data-flag="tg"><span class="flag-icon flag-icon-tg"></span></div>
    <div class="custom-option" data-value="+690" data-flag="tk"><span class="flag-icon flag-icon-tk"></span></div>
    <div class="custom-option" data-value="+676" data-flag="to"><span class="flag-icon flag-icon-to"></span></div>
    <div class="custom-option" data-value="+1868" data-flag="tt"><span class="flag-icon flag-icon-tt"></span></div>
    <div class="custom-option" data-value="+216" data-flag="tn"><span class="flag-icon flag-icon-tn"></span></div>
    <div class="custom-option" data-value="+90" data-flag="tr"><span class="flag-icon flag-icon-tr"></span></div>
    <div class="custom-option" data-value="+993" data-flag="tm"><span class="flag-icon flag-icon-tm"></span></div>
    <div class="custom-option" data-value="+256" data-flag="ug"><span class="flag-icon flag-icon-ug"></span></div>
    <div class="custom-option" data-value="+380" data-flag="ua"><span class="flag-icon flag-icon-ua"></span></div>
    <div class="custom-option" data-value="+598" data-flag="uy"><span class="flag-icon flag-icon-uy"></span></div>
    <div class="custom-option" data-value="+998" data-flag="uz"><span class="flag-icon flag-icon-uz"></span></div>
    <div class="custom-option" data-value="+58" data-flag="ve"><span class="flag-icon flag-icon-ve"></span></div>
    <div class="custom-option" data-value="+84" data-flag="vn"><span class="flag-icon flag-icon-vn"></span></div>
    <div class="custom-option" data-value="+967" data-flag="ye"><span class="flag-icon flag-icon-ye"></span></div>
    <div class="custom-option" data-value="+260" data-flag="zm"><span class="flag-icon flag-icon-zm"></span></div>
    <div class="custom-option" data-value="+263" data-flag="zw"><span class="flag-icon flag-icon-zw"></span></div>
</div>
