<!-- Hidden input to store the selected value -->
<input type="hidden" id="countrySelect" value="+212">

<!-- Custom Dropdown Trigger -->
<div class="custom-select-trigger" id="countryTrigger" tabindex="0">
    <span class="fi fi-ma" id="selectedFlag"></span>
    <i class="fa-solid fa-chevron-down ms-2" style="font-size: 0.7rem; color: #666;"></i>
</div>

<!-- Custom Dropdown Options -->
<div class="custom-options" id="countryOptions">
    <div class="custom-option selected" data-value="+212" data-flag="ma"><span class="fi fi-ma"></span></div>
    <div class="custom-option" data-value="+93" data-flag="af"><span class="fi fi-af"></span></div>
    <div class="custom-option" data-value="+355" data-flag="al"><span class="fi fi-al"></span></div>
    <div class="custom-option" data-value="+213" data-flag="dz"><span class="fi fi-dz"></span></div>
    <div class="custom-option" data-value="+1-684" data-flag="as"><span class="fi fi-as"></span></div>
    <div class="custom-option" data-value="+376" data-flag="ad"><span class="fi fi-ad"></span></div>
    <div class="custom-option" data-value="+244" data-flag="ao"><span class="fi fi-ao"></span></div>
    <div class="custom-option" data-value="+1-264" data-flag="ai"><span class="fi fi-ai"></span></div>
    <div class="custom-option" data-value="+672" data-flag="aq"><span class="fi fi-aq"></span></div>
    <div class="custom-option" data-value="+1-268" data-flag="ag"><span class="fi fi-ag"></span></div>
    <div class="custom-option" data-value="+54" data-flag="ar"><span class="fi fi-ar"></span></div>
    <div class="custom-option" data-value="+374" data-flag="am"><span class="fi fi-am"></span></div>
    <div class="custom-option" data-value="+297" data-flag="aw"><span class="fi fi-aw"></span></div>
    <div class="custom-option" data-value="+61" data-flag="au"><span class="fi fi-au"></span></div>
    <div class="custom-option" data-value="+43" data-flag="at"><span class="fi fi-at"></span></div>
    <div class="custom-option" data-value="+994" data-flag="az"><span class="fi fi-az"></span></div>
    <div class="custom-option" data-value="+1-242" data-flag="bs"><span class="fi fi-bs"></span></div>
    <div class="custom-option" data-value="+973" data-flag="bh"><span class="fi fi-bh"></span></div>
    <div class="custom-option" data-value="+880" data-flag="bd"><span class="fi fi-bd"></span></div>
    <div class="custom-option" data-value="+1-246" data-flag="bb"><span class="fi fi-bb"></span></div>
    <div class="custom-option" data-value="+375" data-flag="by"><span class="fi fi-by"></span></div>
    <div class="custom-option" data-value="+32" data-flag="be"><span class="fi fi-be"></span></div>
    <div class="custom-option" data-value="+501" data-flag="bz"><span class="fi fi-bz"></span></div>
    <div class="custom-option" data-value="+229" data-flag="bj"><span class="fi fi-bj"></span></div>
    <div class="custom-option" data-value="+1-441" data-flag="bm"><span class="fi fi-bm"></span></div>
    <div class="custom-option" data-value="+975" data-flag="bt"><span class="fi fi-bt"></span></div>
    <div class="custom-option" data-value="+591" data-flag="bo"><span class="fi fi-bo"></span></div>
    <div class="custom-option" data-value="+387" data-flag="ba"><span class="fi fi-ba"></span></div>
    <div class="custom-option" data-value="+267" data-flag="bw"><span class="fi fi-bw"></span></div>
    <div class="custom-option" data-value="+55" data-flag="br"><span class="fi fi-br"></span></div>
    <div class="custom-option" data-value="+246" data-flag="io"><span class="fi fi-io"></span></div>
    <div class="custom-option" data-value="+1-284" data-flag="vg"><span class="fi fi-vg"></span></div>
    <div class="custom-option" data-value="+673" data-flag="bn"><span class="fi fi-bn"></span></div>
    <div class="custom-option" data-value="+359" data-flag="bg"><span class="fi fi-bg"></span></div>
    <div class="custom-option" data-value="+226" data-flag="bf"><span class="fi fi-bf"></span></div>
    <div class="custom-option" data-value="+257" data-flag="bi"><span class="fi fi-bi"></span></div>
    <div class="custom-option" data-value="+855" data-flag="kh"><span class="fi fi-kh"></span></div>
    <div class="custom-option" data-value="+237" data-flag="cm"><span class="fi fi-cm"></span></div>
    <div class="custom-option" data-value="+1" data-flag="ca"><span class="fi fi-ca"></span></div>
    <div class="custom-option" data-value="+238" data-flag="cv"><span class="fi fi-cv"></span></div>
    <div class="custom-option" data-value="+1-345" data-flag="ky"><span class="fi fi-ky"></span></div>
    <div class="custom-option" data-value="+236" data-flag="cf"><span class="fi fi-cf"></span></div>
    <div class="custom-option" data-value="+235" data-flag="td"><span class="fi fi-td"></span></div>
    <div class="custom-option" data-value="+56" data-flag="cl"><span class="fi fi-cl"></span></div>
    <div class="custom-option" data-value="+86" data-flag="cn"><span class="fi fi-cn"></span></div>
    <div class="custom-option" data-value="+61" data-flag="cx"><span class="fi fi-cx"></span></div>
    <div class="custom-option" data-value="+61" data-flag="cc"><span class="fi fi-cc"></span></div>
    <div class="custom-option" data-value="+57" data-flag="co"><span class="fi fi-co"></span></div>
    <div class="custom-option" data-value="+269" data-flag="km"><span class="fi fi-km"></span></div>
    <div class="custom-option" data-value="+682" data-flag="ck"><span class="fi fi-ck"></span></div>
    <div class="custom-option" data-value="+506" data-flag="cr"><span class="fi fi-cr"></span></div>
    <div class="custom-option" data-value="+385" data-flag="hr"><span class="fi fi-hr"></span></div>
    <div class="custom-option" data-value="+53" data-flag="cu"><span class="fi fi-cu"></span></div>
    <div class="custom-option" data-value="+599" data-flag="cw"><span class="fi fi-cw"></span></div>
    <div class="custom-option" data-value="+357" data-flag="cy"><span class="fi fi-cy"></span></div>
    <div class="custom-option" data-value="+420" data-flag="cz"><span class="fi fi-cz"></span></div>
    <div class="custom-option" data-value="+243" data-flag="cd"><span class="fi fi-cd"></span></div>
    <div class="custom-option" data-value="+45" data-flag="dk"><span class="fi fi-dk"></span></div>
    <div class="custom-option" data-value="+253" data-flag="dj"><span class="fi fi-dj"></span></div>
    <div class="custom-option" data-value="+1-767" data-flag="dm"><span class="fi fi-dm"></span></div>
    <div class="custom-option" data-value="+1-809" data-flag="do"><span class="fi fi-do"></span></div>
    <div class="custom-option" data-value="+670" data-flag="tl"><span class="fi fi-tl"></span></div>
    <div class="custom-option" data-value="+593" data-flag="ec"><span class="fi fi-ec"></span></div>
    <div class="custom-option" data-value="+20" data-flag="eg"><span class="fi fi-eg"></span></div>
    <div class="custom-option" data-value="+503" data-flag="sv"><span class="fi fi-sv"></span></div>
    <div class="custom-option" data-value="+240" data-flag="gq"><span class="fi fi-gq"></span></div>
    <div class="custom-option" data-value="+291" data-flag="er"><span class="fi fi-er"></span></div>
    <div class="custom-option" data-value="+372" data-flag="ee"><span class="fi fi-ee"></span></div>
    <div class="custom-option" data-value="+251" data-flag="et"><span class="fi fi-et"></span></div>
    <div class="custom-option" data-value="+500" data-flag="fk"><span class="fi fi-fk"></span></div>
    <div class="custom-option" data-value="+298" data-flag="fo"><span class="fi fi-fo"></span></div>
    <div class="custom-option" data-value="+679" data-flag="fj"><span class="fi fi-fj"></span></div>
    <div class="custom-option" data-value="+358" data-flag="fi"><span class="fi fi-fi"></span></div>
    <div class="custom-option" data-value="+33" data-flag="fr"><span class="fi fi-fr"></span></div>
    <div class="custom-option" data-value="+689" data-flag="pf"><span class="fi fi-pf"></span></div>
    <div class="custom-option" data-value="+241" data-flag="ga"><span class="fi fi-ga"></span></div>
    <div class="custom-option" data-value="+220" data-flag="gm"><span class="fi fi-gm"></span></div>
    <div class="custom-option" data-value="+995" data-flag="ge"><span class="fi fi-ge"></span></div>
    <div class="custom-option" data-value="+49" data-flag="de"><span class="fi fi-de"></span></div>
    <div class="custom-option" data-value="+233" data-flag="gh"><span class="fi fi-gh"></span></div>
    <div class="custom-option" data-value="+350" data-flag="gi"><span class="fi fi-gi"></span></div>
    <div class="custom-option" data-value="+30" data-flag="gr"><span class="fi fi-gr"></span></div>
    <div class="custom-option" data-value="+299" data-flag="gl"><span class="fi fi-gl"></span></div>
    <div class="custom-option" data-value="+1-473" data-flag="gd"><span class="fi fi-gd"></span></div>
    <div class="custom-option" data-value="+1-671" data-flag="gu"><span class="fi fi-gu"></span></div>
    <div class="custom-option" data-value="+502" data-flag="gt"><span class="fi fi-gt"></span></div>
    <div class="custom-option" data-value="+44-1481" data-flag="gg"><span class="fi fi-gg"></span></div>
    <div class="custom-option" data-value="+224" data-flag="gn"><span class="fi fi-gn"></span></div>
    <div class="custom-option" data-value="+245" data-flag="gw"><span class="fi fi-gw"></span></div>
    <div class="custom-option" data-value="+592" data-flag="gy"><span class="fi fi-gy"></span></div>
    <div class="custom-option" data-value="+509" data-flag="ht"><span class="fi fi-ht"></span></div>
    <div class="custom-option" data-value="+504" data-flag="hn"><span class="fi fi-hn"></span></div>
    <div class="custom-option" data-value="+852" data-flag="hk"><span class="fi fi-hk"></span></div>
    <div class="custom-option" data-value="+36" data-flag="hu"><span class="fi fi-hu"></span></div>
    <div class="custom-option" data-value="+354" data-flag="is"><span class="fi fi-is"></span></div>
    <div class="custom-option" data-value="+91" data-flag="in"><span class="fi fi-in"></span></div>
    <div class="custom-option" data-value="+62" data-flag="id"><span class="fi fi-id"></span></div>
    <div class="custom-option" data-value="+98" data-flag="ir"><span class="fi fi-ir"></span></div>
    <div class="custom-option" data-value="+964" data-flag="iq"><span class="fi fi-iq"></span></div>
    <div class="custom-option" data-value="+353" data-flag="ie"><span class="fi fi-ie"></span></div>
    <div class="custom-option" data-value="+44-1624" data-flag="im"><span class="fi fi-im"></span></div>
    <div class="custom-option" data-value="+972" data-flag="il"><span class="fi fi-il"></span></div>
    <div class="custom-option" data-value="+39" data-flag="it"><span class="fi fi-it"></span></div>
    <div class="custom-option" data-value="+225" data-flag="ci"><span class="fi fi-ci"></span></div>
    <div class="custom-option" data-value="+1-876" data-flag="jm"><span class="fi fi-jm"></span></div>
    <div class="custom-option" data-value="+81" data-flag="jp"><span class="fi fi-jp"></span></div>
    <div class="custom-option" data-value="+44-1534" data-flag="je"><span class="fi fi-je"></span></div>
    <div class="custom-option" data-value="+962" data-flag="jo"><span class="fi fi-jo"></span></div>
    <div class="custom-option" data-value="+7" data-flag="kz"><span class="fi fi-kz"></span></div>
    <div class="custom-option" data-value="+254" data-flag="ke"><span class="fi fi-ke"></span></div>
    <div class="custom-option" data-value="+686" data-flag="ki"><span class="fi fi-ki"></span></div>
    <div class="custom-option" data-value="+383" data-flag="xk"><span class="fi fi-xk"></span></div>
    <div class="custom-option" data-value="+965" data-flag="kw"><span class="fi fi-kw"></span></div>
    <div class="custom-option" data-value="+996" data-flag="kg"><span class="fi fi-kg"></span></div>
    <div class="custom-option" data-value="+856" data-flag="la"><span class="fi fi-la"></span></div>
    <div class="custom-option" data-value="+371" data-flag="lv"><span class="fi fi-lv"></span></div>
    <div class="custom-option" data-value="+961" data-flag="lb"><span class="fi fi-lb"></span></div>
    <div class="custom-option" data-value="+266" data-flag="ls"><span class="fi fi-ls"></span></div>
    <div class="custom-option" data-value="+231" data-flag="lr"><span class="fi fi-lr"></span></div>
    <div class="custom-option" data-value="+218" data-flag="ly"><span class="fi fi-ly"></span></div>
    <div class="custom-option" data-value="+423" data-flag="li"><span class="fi fi-li"></span></div>
    <div class="custom-option" data-value="+370" data-flag="lt"><span class="fi fi-lt"></span></div>
    <div class="custom-option" data-value="+352" data-flag="lu"><span class="fi fi-lu"></span></div>
    <div class="custom-option" data-value="+853" data-flag="mo"><span class="fi fi-mo"></span></div>
    <div class="custom-option" data-value="+389" data-flag="mk"><span class="fi fi-mk"></span></div>
    <div class="custom-option" data-value="+261" data-flag="mg"><span class="fi fi-mg"></span></div>
    <div class="custom-option" data-value="+265" data-flag="mw"><span class="fi fi-mw"></span></div>
    <div class="custom-option" data-value="+60" data-flag="my"><span class="fi fi-my"></span></div>
    <div class="custom-option" data-value="+960" data-flag="mv"><span class="fi fi-mv"></span></div>
    <div class="custom-option" data-value="+223" data-flag="ml"><span class="fi fi-ml"></span></div>
    <div class="custom-option" data-value="+356" data-flag="mt"><span class="fi fi-mt"></span></div>
    <div class="custom-option" data-value="+692" data-flag="mh"><span class="fi fi-mh"></span></div>
    <div class="custom-option" data-value="+222" data-flag="mr"><span class="fi fi-mr"></span></div>
    <div class="custom-option" data-value="+230" data-flag="mu"><span class="fi fi-mu"></span></div>
    <div class="custom-option" data-value="+262" data-flag="yt"><span class="fi fi-yt"></span></div>
    <div class="custom-option" data-value="+52" data-flag="mx"><span class="fi fi-mx"></span></div>
    <div class="custom-option" data-value="+691" data-flag="fm"><span class="fi fi-fm"></span></div>
    <div class="custom-option" data-value="+373" data-flag="md"><span class="fi fi-md"></span></div>
    <div class="custom-option" data-value="+377" data-flag="mc"><span class="fi fi-mc"></span></div>
    <div class="custom-option" data-value="+976" data-flag="mn"><span class="fi fi-mn"></span></div>
    <div class="custom-option" data-value="+382" data-flag="me"><span class="fi fi-me"></span></div>
    <div class="custom-option" data-value="+1-664" data-flag="ms"><span class="fi fi-ms"></span></div>
    <div class="custom-option" data-value="+212" data-flag="ma"><span class="fi fi-ma"></span></div>
    <div class="custom-option" data-value="+258" data-flag="mz"><span class="fi fi-mz"></span></div>
    <div class="custom-option" data-value="+95" data-flag="mm"><span class="fi fi-mm"></span></div>
    <div class="custom-option" data-value="+264" data-flag="na"><span class="fi fi-na"></span></div>
    <div class="custom-option" data-value="+674" data-flag="nr"><span class="fi fi-nr"></span></div>
    <div class="custom-option" data-value="+977" data-flag="np"><span class="fi fi-np"></span></div>
    <div class="custom-option" data-value="+31" data-flag="nl"><span class="fi fi-nl"></span></div>
    <div class="custom-option" data-value="+599" data-flag="an"><span class="fi fi-an"></span></div>
    <div class="custom-option" data-value="+687" data-flag="nc"><span class="fi fi-nc"></span></div>
    <div class="custom-option" data-value="+64" data-flag="nz"><span class="fi fi-nz"></span></div>
    <div class="custom-option" data-value="+505" data-flag="ni"><span class="fi fi-ni"></span></div>
    <div class="custom-option" data-value="+227" data-flag="ne"><span class="fi fi-ne"></span></div>
    <div class="custom-option" data-value="+234" data-flag="ng"><span class="fi fi-ng"></span></div>
    <div class="custom-option" data-value="+683" data-flag="nu"><span class="fi fi-nu"></span></div>
    <div class="custom-option" data-value="+850" data-flag="kp"><span class="fi fi-kp"></span></div>
    <div class="custom-option" data-value="+1-670" data-flag="mp"><span class="fi fi-mp"></span></div>
    <div class="custom-option" data-value="+47" data-flag="no"><span class="fi fi-no"></span></div>
    <div class="custom-option" data-value="+968" data-flag="om"><span class="fi fi-om"></span></div>
    <div class="custom-option" data-value="+92" data-flag="pk"><span class="fi fi-pk"></span></div>
    <div class="custom-option" data-value="+680" data-flag="pw"><span class="fi fi-pw"></span></div>
    <div class="custom-option" data-value="+970" data-flag="ps"><span class="fi fi-ps"></span></div>
    <div class="custom-option" data-value="+507" data-flag="pa"><span class="fi fi-pa"></span></div>
    <div class="custom-option" data-value="+675" data-flag="pg"><span class="fi fi-pg"></span></div>
    <div class="custom-option" data-value="+595" data-flag="py"><span class="fi fi-py"></span></div>
    <div class="custom-option" data-value="+51" data-flag="pe"><span class="fi fi-pe"></span></div>
    <div class="custom-option" data-value="+63" data-flag="ph"><span class="fi fi-ph"></span></div>
    <div class="custom-option" data-value="+64" data-flag="pn"><span class="fi fi-pn"></span></div>
    <div class="custom-option" data-value="+48" data-flag="pl"><span class="fi fi-pl"></span></div>
    <div class="custom-option" data-value="+351" data-flag="pt"><span class="fi fi-pt"></span></div>
    <div class="custom-option" data-value="+1-787" data-flag="pr"><span class="fi fi-pr"></span></div>
    <div class="custom-option" data-value="+974" data-flag="qa"><span class="fi fi-qa"></span></div>
    <div class="custom-option" data-value="+242" data-flag="cg"><span class="fi fi-cg"></span></div>
    <div class="custom-option" data-value="+40" data-flag="ro"><span class="fi fi-ro"></span></div>
    <div class="custom-option" data-value="+7" data-flag="ru"><span class="fi fi-ru"></span></div>
    <div class="custom-option" data-value="+250" data-flag="rw"><span class="fi fi-rw"></span></div>
    <div class="custom-option" data-value="+590" data-flag="bl"><span class="fi fi-bl"></span></div>
    <div class="custom-option" data-value="+290" data-flag="sh"><span class="fi fi-sh"></span></div>
    <div class="custom-option" data-value="+1-869" data-flag="kn"><span class="fi fi-kn"></span></div>
    <div class="custom-option" data-value="+1-758" data-flag="lc"><span class="fi fi-lc"></span></div>
    <div class="custom-option" data-value="+590" data-flag="mf"><span class="fi fi-mf"></span></div>
    <div class="custom-option" data-value="+508" data-flag="pm"><span class="fi fi-pm"></span></div>
    <div class="custom-option" data-value="+1-784" data-flag="vc"><span class="fi fi-vc"></span></div>
    <div class="custom-option" data-value="+685" data-flag="ws"><span class="fi fi-ws"></span></div>
    <div class="custom-option" data-value="+378" data-flag="sm"><span class="fi fi-sm"></span></div>
    <div class="custom-option" data-value="+239" data-flag="st"><span class="fi fi-st"></span></div>
    <div class="custom-option" data-value="+966" data-flag="sa"><span class="fi fi-sa"></span></div>
    <div class="custom-option" data-value="+221" data-flag="sn"><span class="fi fi-sn"></span></div>
    <div class="custom-option" data-value="+381" data-flag="rs"><span class="fi fi-rs"></span></div>
    <div class="custom-option" data-value="+248" data-flag="sc"><span class="fi fi-sc"></span></div>
    <div class="custom-option" data-value="+232" data-flag="sl"><span class="fi fi-sl"></span></div>
    <div class="custom-option" data-value="+65" data-flag="sg"><span class="fi fi-sg"></span></div>
    <div class="custom-option" data-value="+1-721" data-flag="sx"><span class="fi fi-sx"></span></div>
    <div class="custom-option" data-value="+421" data-flag="sk"><span class="fi fi-sk"></span></div>
    <div class="custom-option" data-value="+386" data-flag="si"><span class="fi fi-si"></span></div>
    <div class="custom-option" data-value="+677" data-flag="sb"><span class="fi fi-sb"></span></div>
    <div class="custom-option" data-value="+252" data-flag="so"><span class="fi fi-so"></span></div>
    <div class="custom-option" data-value="+27" data-flag="za"><span class="fi fi-za"></span></div>
    <div class="custom-option" data-value="+82" data-flag="kr"><span class="fi fi-kr"></span></div>
    <div class="custom-option" data-value="+211" data-flag="ss"><span class="fi fi-ss"></span></div>
    <div class="custom-option" data-value="+34" data-flag="es"><span class="fi fi-es"></span></div>
    <div class="custom-option" data-value="+94" data-flag="lk"><span class="fi fi-lk"></span></div>
    <div class="custom-option" data-value="+249" data-flag="sd"><span class="fi fi-sd"></span></div>
    <div class="custom-option" data-value="+597" data-flag="sr"><span class="fi fi-sr"></span></div>
    <div class="custom-option" data-value="+47" data-flag="sj"><span class="fi fi-sj"></span></div>
    <div class="custom-option" data-value="+268" data-flag="sz"><span class="fi fi-sz"></span></div>
    <div class="custom-option" data-value="+46" data-flag="se"><span class="fi fi-se"></span></div>
    <div class="custom-option" data-value="+41" data-flag="ch"><span class="fi fi-ch"></span></div>
    <div class="custom-option" data-value="+963" data-flag="sy"><span class="fi fi-sy"></span></div>
    <div class="custom-option" data-value="+886" data-flag="tw"><span class="fi fi-tw"></span></div>
    <div class="custom-option" data-value="+992" data-flag="tj"><span class="fi fi-tj"></span></div>
    <div class="custom-option" data-value="+255" data-flag="tz"><span class="fi fi-tz"></span></div>
    <div class="custom-option" data-value="+66" data-flag="th"><span class="fi fi-th"></span></div>
    <div class="custom-option" data-value="+228" data-flag="tg"><span class="fi fi-tg"></span></div>
    <div class="custom-option" data-value="+690" data-flag="tk"><span class="fi fi-tk"></span></div>
    <div class="custom-option" data-value="+676" data-flag="to"><span class="fi fi-to"></span></div>
    <div class="custom-option" data-value="+1-868" data-flag="tt"><span class="fi fi-tt"></span></div>
    <div class="custom-option" data-value="+216" data-flag="tn"><span class="fi fi-tn"></span></div>
    <div class="custom-option" data-value="+90" data-flag="tr"><span class="fi fi-tr"></span></div>
    <div class="custom-option" data-value="+993" data-flag="tm"><span class="fi fi-tm"></span></div>
    <div class="custom-option" data-value="+1-649" data-flag="tc"><span class="fi fi-tc"></span></div>
    <div class="custom-option" data-value="+688" data-flag="tv"><span class="fi fi-tv"></span></div>
    <div class="custom-option" data-value="+256" data-flag="ug"><span class="fi fi-ug"></span></div>
    <div class="custom-option" data-value="+380" data-flag="ua"><span class="fi fi-ua"></span></div>
    <div class="custom-option" data-value="+971" data-flag="ae"><span class="fi fi-ae"></span></div>
    <div class="custom-option" data-value="+44" data-flag="gb"><span class="fi fi-gb"></span></div>
    <div class="custom-option" data-value="+1" data-flag="us"><span class="fi fi-us"></span></div>
    <div class="custom-option" data-value="+598" data-flag="uy"><span class="fi fi-uy"></span></div>
    <div class="custom-option" data-value="+998" data-flag="uz"><span class="fi fi-uz"></span></div>
    <div class="custom-option" data-value="+58" data-flag="ve"><span class="fi fi-ve"></span></div>
    <div class="custom-option" data-value="+84" data-flag="vn"><span class="fi fi-vn"></span></div>
    <div class="custom-option" data-value="+1-284" data-flag="vi"><span class="fi fi-vi"></span></div>
    <div class="custom-option" data-value="+681" data-flag="wf"><span class="fi fi-wf"></span></div>
    <div class="custom-option" data-value="+967" data-flag="ye"><span class="fi fi-ye"></span></div>
    <div class="custom-option" data-value="+260" data-flag="zm"><span class="fi fi-zm"></span></div>
    <div class="custom-option" data-value="+263" data-flag="zw"><span class="fi fi-zw"></span></div>
</div>