
ALTER TABLE users
ADD COLUMN Rue VARCHAR(255) NULL AFTER address,
ADD COLUMN Numero VARCHAR(50) NULL AFTER Rue,
ADD COLUMN Ville VARCHAR(100) NULL AFTER Numero,
ADD COLUMN Codepostal VARCHAR(20) NULL AFTER Ville;


ALTER TABLE users
ADD COLUMN num_vat VARCHAR(50)  AFTER Codepostal;